### ISSUE TITLE
Catmandu dropping non-latin fields when exporting as MARCMaker

### ISSUE THREAD

**Issue by powerriegel** [LibreCat/Catmandu-MARC#111]
When converting the attached file with the command
`catmandu convert MARC to MARC --type MARCMaker < oschrift_me.mrc`

the non-latin fields are dropped. This happens only when exporting in MARCMaker, not in XML. 
[oschrift_me.zip](https://github.com/LibreCat/Catmandu/files/7283736/oschrift_me.zip)

Version 1.254 on Ubuntu 20.04. 
[oschrift_me.zip](https://github.com/LibreCat/Catmandu/files/7283753/oschrift_me.zip)

**Comment by phochste** [comment]
Fixed in the 1.26 release now available on CPAN
