### ISSUE TITLE
Provide an alias (or rename) ISO to the USMARC exporter

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu-MARC#20]
ISO is a better name for MARC types

    $ catmandu convert MARC --type XML to MARC --type ISO < data.xml

**Comment by jorol** [comment]
as hack de0e587a6aceb9e16e5f4b48d7698d2b4f4af18b or do you want a more generic solution?

**Comment by phochste** [comment]
Looks good. It is more about the mad choice I made in the past to name this format USMARC where ISO-something would have be a better choice.

**Comment by phochste** [comment]
thanks!
