### ISSUE TITLE
Parsing of MARC XML generates a warning

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu-MARC#22]
Parsing XML files with MARC::File::XML (1.0.3) generates a warning

    Use of uninitialized value in concatenation (.) or string at /opt/lludss-   import/local/lib/perl5/MARC/File/XML.pm line 397, <GEN0> chunk 3.

Execute

  $ catmandu convert MARC --type XML < marc.xml

where marc.xml like:

    <?xml version="1.0" encoding="UTF-8"?>
    <collection xmlns="http://www.loc.gov/MARC21/slim">
    <record>
    <leader>     cam a22     3u 4500</leader>
    <controlfield tag="001">530000001</controlfield>
    </record>
    </collection>

**Comment by phochste** [comment]
Reported to MARC::File::XML as bug

**Comment by jorol** [comment]
I can' reproduce the problem:

```terminal
$ catmandu convert MARC --type XML to JSON < marc.xml
{"record":[["LDR",null,null,"_","     cam a22     3u 4500"], "001",null,null,"_","530000001"]],"_id":"530000001"}
```
Which version of modules are installed on your system?

**Comment by phochste** [comment]
catmandu (Catmandu::CLI) version 0.9505 (/opt/lludss-import/local/bin/catmandu)
Catmandu::MARC 0.213
MARC::JSON               |         |
MARC::Batch              |         | Perl module for handling files of MARC::Record objects
MARC::Record             | 2.0.6   | Perl extension for handling MARC records
MARC::Field              |         | Perl extension for handling MARC fields
MARC::File               |         | Base class for files of MARC records
MARC::Charset            | 1.35    | convert MARC-8 encoded strings to UTF-8
MARC::Charset::Code      |         | represents a MARC-8/UTF-8 mapping
MARC::Charset::Compiler  |         | compile XML mapping rules from LoC
MARC::Charset::Table     |         |
MARC::Charset::Constants |         |
MARC::File::MARCMaker    | 0.05    | - Work with MARCMaker/MARCBreaker records.
MARC::File::USMARC       |         | USMARC-specific file handling
MARC::File::Encode       |         |
MARC::File::MiJ          | 0.04    | Read newline-delimited marc-in-json files
MARC::File::XML          | 1.0.3   | Work with MARC data encoded as XML
MARC::File::MicroLIF     |         | MicroLIF-specific file handling
MARC::Parser::RAW        | 0.03    | Parser for ISO 2709 encoded MARC records
MARC::Record::MiJ        | 0.04    | Convert MARC::Record to/from marc-in-json structure

**Comment by jorol** [comment]
I have same configuration except:

perl 5.18.2
Catmandu::MARC 0.214

**Comment by phochste** [comment]
I have the same on Catmandu::MARC 0.214

**Comment by jorol** [comment]
Ok, tested again on a LInux machine and can reproduce it there:

Debian 3.2.65-1+deb7u2 x86_64 GNU/Linux
perl v5.20.2 built for x86_64-linux

**Comment by jorol** [comment]
My bugfix was merged https://github.com/perl4lib/marc-perl/pull/3, but no new cpan release yet. As an alternative I implemented  a new (faster) parser https://github.com/jorol/MARC-Parser-XML/, but I'm not sure if that would be a good solution for the long term.

**Comment by njahn82** [comment]
I got the same problem. I tried to convert [INSPIRE HEP Marc-XML Dump](http://inspirehep.net/dumps/inspire-dump.html) into json on the command line to avoid xml event parsing in R.

```
$ catmandu convert MARC --type XML to JSON < test_hep.xml > test.json
Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/MARC/File/XML.pm line 397, <GEN0> chunk 17.
```
Any other suggestion to get this job done on the CLI?

**Comment by njahn82** [comment]
Upps, should have checked test.json, looks workable, thank you!

**Comment by phochste** [comment]
:)
