### ISSUE TITLE
Deprecate the name USMARC in Importers and Exporters in favor of ISO

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu-MARC#34]

**Comment by jorol** [comment]
How do you want implement this? Keeping USMARC with a deprecation warning for some versions or just renaming it to ISO?

**Comment by phochste** [comment]
I would like to rename it to ISO, but keep the USMARC working with a deprecation warning indeed.

**Comment by jorol** [comment]
I've committed this change to https://github.com/jorol/Catmandu-MARC/tree/gh%2334. Tests run fine locally, but I still got a test failure on Travis  :

```terminal
t/99-deprecate.t ..................... Oops! Importer "USMARC" is deprecated. Use "ISO" instead. at (eval 257)[/home/travis/perl5/perlbrew/perls/5.20/lib/site_perl/5.20.0/Sub/Quote.pm:5] line 162.

t/99-deprecate.t ..................... Dubious, test returned 255 (wstat 65280, 0xff00)
```

@phochste could you please have a look at it https://github.com/jorol/Catmandu-MARC/blob/gh%2334/t/99-deprecate.t?

**Comment by phochste** [comment]
Hmmm.. on my dev machine perl 5.23.3 and 5.24.0 I don't see a problem..

**Comment by phochste** [comment]
Seems a Travis quirk. I was checking if @karenetheridge had a Travis build for Test::Warnings itself https://travis-ci.org/karenetheridge/Test-Warnings/branches but no.

**Comment by jorol** [comment]
Fixed in #41

**Comment by karenetheridge** [comment]
Is there an issue with Test::Warnings? I haven't gotten around to rolling out travis configs to all my repositories yet.

**Comment by phochste** [comment]
@karenetheridge we tried to deprecate one of our modules by adding into our code:

     warnings::warnif( "deprecated", "Oops! Importer \"USMARC\" is deprecated. Use \"ISO\" instead." );

and use Test::Warnings to test if this warning message works correctly. But apparently the 'cover -test' we use on Travis sees these 'warnings' as error conditions in the test. Was searching on travis to see how you run your test suite on Travis.

**Comment by karenetheridge** [comment]
Strange!  warnif() should behave the same as warn... I have a test for such
a warning here:
https://metacpan.org/source/ETHER/Dist-Zilla-Plugin-Test-EOL-0.19/t/02-eoltests.t

**Comment by jorol** [comment]
@karenetheridge Thanks, it's no problem of Test::Warnings. I've created a simple test module <https://github.com/jorol/xyz>, tests run fine on my local machines, but fail on Travis <https://travis-ci.org/jorol/xyz/jobs/160086323> ...

**Comment by karenetheridge** [comment]
Strange! It would appear that *something* has fatalized the 'deprecated'
class of warnings (i.e. `use warnings FATAL => 'deprecated'`)... you can
confirm this by `diag warnings::fatal_enabled('deprecated')` in the test,
although that won't tell you what in the calling stack made that change.
