### ISSUE TITLE
MARC record structure

### ISSUE THREAD

**Issue by cKlee** [LibreCat/Catmandu-MARC#35]
I'm just wondering. Why is an offset of 5 [here](https://github.com/LibreCat/Catmandu-MARC/blob/master/lib/Catmandu/Fix/Inline/marc_map.pm#L146-L147). Does '_' indicate an empty subfield?

**Comment by phochste** [comment]
This is to provide backwards compatibility. In the past every due to bug non-controll fields also contained an underscore field:

    [ '245' , ' ' , ' ' , '_' , '' , 'a' , 'test ]

vs:

    [ '245' , ' ' , ' ' , 'a' , 'test ]

With these lines both will lead to the same result. The '_' subfield is ignored for non-controll fields

**Comment by cKlee** [comment]
Thanks!
