### ISSUE TITLE
marc_remove() in marc_each generates parsing errors

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu-MARC#37]
With the fix:

   do marc_each()
        if marc_match(245a,'.*')
           marc_remove(245)
        end
   end

generates error:

Oops! One of your fixes threw an error...
Source: Catmandu::Fix::Bind::marc_each=HASH(0x4c0a180)
Error: Can't use an undefined value as an ARRAY reference at /opt/lludss-import/local/lib/perl5/Catmandu/Fix/Bind/marc_each.pm line 33, <GEN0> line 8.

**Comment by jorol** [comment]
Fixed in pr #38.

**Comment by phochste** [comment]
Thanks!
