### ISSUE TITLE
Different formats for Importer and Exporter as default

### ISSUE THREAD

**Issue by jorol** [LibreCat/Catmandu-MARC#40]
Catmandu::Importer::MARC and Catmandu::Exporter::MARC use different types as defaults:

[USMARC](https://github.com/LibreCat/Catmandu-MARC/blob/master/lib/Catmandu/Importer/MARC.pm#L120)

[XML](https://github.com/LibreCat/Catmandu-MARC/blob/master/lib/Catmandu/Exporter/MARC.pm#L72)

It would be more convenient if they would set the same formats as defaults. Could we change that or would it break too many scripts?

**Comment by phochste** [comment]
Yes, version 1.0 is a good start to set this straight. I also want to deprecate that importer/exporter name USMARC as it doesn't state what it does (going from/to ISO format of MARC).

**Comment by jorol** [comment]
Fixed in #42
