### ISSUE TITLE
Implement MARCSpec

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu-MARC#5]
http://cklee.github.io/marc-spec/marc-spec.html

**Comment by cKlee** [comment]
So, what is the best way to contribute?

**Comment by phochste** [comment]
Get the dev branch of Catmandu-MARC locally. Create from this branch a new marcspec branch. And do a pull request on your local branch. This is one way.

Another way is to create a brand new Catmandu::Fix::marc_spec perl repository and work seperately

**Comment by cKlee** [comment]
I don't really know how CPAN works. But both approaches seem to have caveats. With the second approach (work separately) I see the problem with version control. If you increase the version number and mine stays behind, then marc_spec is not available from the current version of Catmandu::MARC. Isn't it? Or is it not a module of Catmandu::MARC at all?

I prefer the first approach. But this means that you're in charge of deployment.

Are there already any contributions?

**Comment by phochste** [comment]
In CPAN you can work in any namespace you like. For instance, I work in the Catmandu namespace for Catmandu::MARC and have other versions etc.

Anyhow it is no problem to include it in Catmandu::MARC github project. Just send me a pull request when you’re ready and I’ll take a look. There already contributions from others. I’ll add your name

> On 16 Jun 2016, at 09:55, Carsten Klee <notifications@github.com> wrote:
> 
> I don't really know how CPAN works. But both approaches seem to have caveats. With the second approach (work separately) I see the problem with version control. If you increase the version number and mine stays behind, then marc_spec is not available from the current version of Catmandu::MARC. Isn't it? Or is it not a module of Catmandu::MARC at all?
> 
> I prefer the first approach. But this means that you're in charge of deployment.
> 
> Are there already any contributions?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Patrick Hochstenbach - digital architect
University Library Ghent
Sint-Hubertusstraat 8 - 9000 Ghent - Belgium
patrick.hochstenbach@ugent.be
+32 (0)9 264 7980

**Comment by cKlee** [comment]
I talked to @jorol and we both think that it might be better to work separately first and look how marc_spec is accepted and if it's worth to merge into Catmandu::MARC core. Thus there will be no additional dependencies in Catmandu (marc_spec depends on [MARC::Spec](https://github.com/MARCspec/MARC-Spec). What do you think?

**Comment by phochste** [comment]
Fine with me. It is done more often in Catmandu to make some modules first separate. Also it give you more freedom and flexibility in the first versions to tune the code on the required needs.

**Comment by cKlee** [comment]
Done. I released [Catmandu::Fix::marc_spec](https://metacpan.org/pod/Catmandu::Fix::marc_spec). Would be nice if Catmandu Docs could give a hint to it, if it's volitional.

**Comment by phochste** [comment]
Super! I'm busy with a rewrite of Catmandu::MARC and will include it!

**Comment by jorol** [comment]
Catmandu::Fix::marc_spec could be installed independently, so no further adaption of Catmandu::MARC necessary.
