### ISSUE TITLE
Integration of marc_spec

### ISSUE THREAD

**Issue by cKlee** [LibreCat/Catmandu-MARC#52]
To facilitate https://github.com/cKlee/Catmandu-Fix-marc_spec/issues/1 I think the best way is to integrate marc_spec into Catmandu::MARC like you did with marc_map. Do you have any concerns about this?
@phochste @nichtich @jorol

**Comment by phochste** [comment]
Hi Carsten, I will work on this

Cheers

P@

**Comment by cKlee** [comment]
Great! Let me know when I can help.

**Comment by phochste** [comment]
Can you give contributor rights or anything to overwrite Camandu-Fix-marc_spec on PAUSE. I don’y this I am allowed to upload a new version of Catmandu::MARC with Catmandu::Fix::marc_spec included

**Comment by cKlee** [comment]
PAUSE said: Added HOCHSTEN to co-maintainers of Catmandu::Fix::marc_spec

**Comment by nichtich** [comment]
For integration if marc_spec and marc_map as outlined at 

* https://github.com/LibreCat/Catmandu-MARC/wiki/Mapping-rules
* https://github.com/LibreCat/Catmandu-MARC/wiki/Mapping-Rules-marc_spec

I'd choose another (shorter) name for `nested_arrays` and optionally allow `$` before subfield indicators.

**Comment by cKlee** [comment]
> and optionally allow $ before subfield indicators. I'd also prefer _ instead of * as wildcard character.

Does this refer to MARCspec? The dollar sign in MARCspec is not optionally. It's necessary because MARCspec syntax can be very complex, Thus parsing subfield specs without the dollar could be very tricky and error prone. The underscore in MARCspec is used to indicate field indicators. MARCspec uses the dot as a wildcard. In my opinion this makes it more easy to match field tags.

**Comment by phochste** [comment]
I can also support the $ tag and _ wildcards. So if there is no big issues I would like to merge into dev next week.

**Comment by cKlee** [comment]
@phochste be aware of https://github.com/LibreCat/Catmandu-MARC/pull/55

**Comment by phochste** [comment]
Ok available in 1.08
