### ISSUE TITLE
Catmandu::MARC::marc_map: Undef values when using $append & split

### ISSUE THREAD

**Issue by cKlee** [LibreCat/Catmandu-MARC#63]
With

    catmandu convert MARC --fix "marc_map(100a,contrib.$append, split:1); retain_field(contrib)" < perl_books.mrc

when field 100 does not exist. Result is

    {"contrib":[null]}

Patch see https://github.com/LibreCat/Catmandu-MARC/pull/62

**Comment by phochste** [comment]
Thanks, patched in #66
