### ISSUE TITLE
MARCXML problem

### ISSUE THREAD

**Issue by cKlee** [LibreCat/Catmandu-MARC#67]
With `prove` I get the following warning:

    t/04-marc21.t ........................ Use of uninitialized value in concatenation (.) or string at ~/perl5/perlbrew/perls/perl-5.20.2/lib/site_perl/5.20.2/MARC/File/XML.pm line 397, <GEN0> chunk 3.

Same warning pops up when trying to convert:

    catmandu convert MARC --type XML --fix "marc_map(022$a, issn); retain(issn)" < marc.xml

```json
...
{"issn":"0176-9820"},
{"iUse of uninitialized value in concatenation (.) or string at ~/perl5/perlbrew/perls/perl-5.20.2/lib/site_perl/5.20.2/MARC/File/XML.pm line 397, <GEN0> chunk 2047.
ssn":"0340-3297"},
...
```

**Comment by jorol** [comment]
Already fixed in #22, but no new release of MARC::XML yet. I will ask Galen to release a new version.
