### ISSUE TITLE
marc_set("FMT", ...) does not work correctly

### ISSUE THREAD

**Issue by CaptSolo** [LibreCat/Catmandu-MARC#79]
The value of "FMT" field can not be changed correctly using marc_set():

Fix: `marc_set("FMT", "AU")`

Input data:

```
      [
         "FMT",
         " ",
         " ",
         "_",
         "BK"
      ],
```

Result:

```
      [
         "FMT",
         " ",
         " ",
         "_",
         "BK",
         "a",
         "AU"
      ],
```

**Comment by CaptSolo** [comment]
Workaround: `set_field(record.0.4, 'AU')`

**Comment by phochste** [comment]
The correct syntax is:

```
marc_set(FMT_,AU)
```

But I'll see if I can add default support for what you try to do

**Comment by CaptSolo** [comment]
I tried `marc_set(FMT_,AU)` but it did not work correctly either :

```
      [
         "FMT",
         " ",
         " ",
         "_",
         "BK",
         "[_]",
         "AU"
      ],
```

**Comment by phochste** [comment]
Can you see which version of Catmandu::MARC you have?

```
$ catmandu info | grep Catmandu::MARC
```

**Comment by phochste** [comment]
Version 1.17 is on its way to CPAN

**Comment by CaptSolo** [comment]
My mistake: I had an old version in a Docker image.

Both versions – `marc_set(FMT_,AU)` and `marc_set("FMT", "AU")` – work fine with version 1.161.

Sorry for the confusion.
