### ISSUE TITLE
Incorrect MARC tag value type (numeric, not a string) in set_field()

### ISSUE THREAD

**Issue by CaptSolo** [LibreCat/Catmandu-MARC#82]
When editing a MARC record retrieved via `marc_copy` incorrect MARC tag value type (numeric, not a string) is set when using `set_field()` :

Code:

```
marc_copy(100, tmp)
set_field(tmp.0.tag, "910")
marc_paste(tmp)
```

The resulting tag value is `910` not `"910"` :
```
   "tmp" : [
      {
         "tag" : 910,
         "ind1" : "1",
         "ind2" : " ",
         "subfields" : [
            {
               "a" : "Birzvalka, Irēna,"
            },
            {
               "d" : "1936-"
            }
         ]
      }
   ],
```

This is not a major problem as marc_paste understands it anyway however that is inconsistent with how imported MARC records are represented.

**Comment by phochste** [comment]
This is not a Catmandu::MARC issue but a Catmandu issue. I created a new ticket for that.

One can always create a literal string:

```
string(tmp.0.tag)
```
