### ISSUE TITLE
Add a marc_sort Fix

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu-MARC#94]
This Fix will sort all the tags in the MARC record but keep the tags of the same field untouched. E.g.

```
999 $aABC
100 $aXYZ
005 $a987$b654
245 $aBlala
005 $a321
```

will become after a sort

```
005 $a987$b654
005 $a321
100 $aXYZ
245 $aBlala
999 $aABC
```

**Comment by jorol** [comment]
Fixed in v1.252
